### ISSUE TITLE
エラーハンドリング

### ISSUE THREAD

**Issue by ktsn** [ktsn/float-behind#12]
つらそう。

**Comment by ktsn** [comment]
@TETRA2000 
エラーの時はこういう感じでレスポンス返すのはどうでしょうか？

```js
{
    "errors": [
        {
            "param": "id",
            "message": "Invalid param",
            "value": "test"
        }
    ],
    "code": 400
}
```

**Comment by TETRA2000** [comment]
@ktsn  ナイス！ちなみに、`code`はステータスコード？
エラーコードなら、エラーごとに個別にもたせてやった方がいい気がします。
http://qiita.com/suin/items/f7ac4de914e9f3f35884

**Comment by ktsn** [comment]
ステータスコードですー。

**Comment by ktsn** [comment]
エラーコード定義しておくべきですかね？
はじめのうちはステータスコードのみで十分な気がして入れてないですが。

**Comment by TETRA2000** [comment]
@ktsn 多言語化する予定がなければいい気がします。

**Comment by ktsn** [comment]
多言語化とエラーコードってどういう関係があるんですか？

**Comment by TETRA2000** [comment]
@ktsn クライアント側で画面にエラーメッセージ出す場合
(例えば、「URLを貼れ！」的なの)

クライアントにコードと文言の対応表持たせる感じかな？
って思ったので。

**Comment by ktsn** [comment]
あー、なるほど。
今のところ個別にエラーメッセージ出すようなケースもないし、今は考えなくても良いかな。

**Comment by TETRA2000** [comment]
了解です！

**Comment by ktsn** [comment]
よくよく考えたら複数のエラーを返すケースないし、将来的にもほんの一部になると思うので、`error` にしようかと思います。
もし複数返すことになったら、`error` の中でいい感じにやるということにしたいです。
(いちいち配列を走査するのめんどい)

あと、`code` -> `status` にしますか。
```js
{
    "error": {
        "param": "id",
        "message": "Invalid param", // <-- required
        "value": "test"
    },
    "status": 400
}
```

**Comment by TETRA2000** [comment]
@ktsn  OKです
Simple is the best!!
